import type { VercelRequest, VercelResponse } from '@vercel/node';
import { ai, validateImagePayload, withTimeout } from './_utils.js';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { imageBase64, mimeType, maskTarget } = req.body as {
    imageBase64: string;
    mimeType: string;
    maskTarget: string;
  };

  if (!imageBase64 || !maskTarget) {
    return res.status(400).json({ error: 'Missing required fields: imageBase64, maskTarget.' });
  }

  try {
    validateImagePayload(imageBase64, mimeType);
    const targetLower = maskTarget.toLowerCase();
    const allExclusions = [
      'roof', 'windows', 'window frames', 'shutters', 'doors', 'garage doors',
      'trim', 'gutters', 'downspouts', 'fascia', 'soffits', 'foundation',
      'concrete', 'sky', 'grass', 'trees', 'plants', 'people', 'vehicles', 'shadows',
    ];
    const activeExclusions = allExclusions.filter(e => !targetLower.includes(e));

    const response = await withTimeout(
      ai.models.generateContent({
        model: 'gemini-3.1-flash-image-preview',
        contents: {
          parts: [
            { inlineData: { data: imageBase64, mimeType: mimeType || 'image/png' } },
            {
              text: `Create a pixel-perfect, high-contrast binary segmentation mask (black and white only) for the following target: "${maskTarget}".
              
CRITICAL RULES:
1. The ${maskTarget} MUST be PURE WHITE (#FFFFFF).
2. EVERYTHING ELSE MUST be PURE BLACK (#000000).
3. EXCLUDE: ${activeExclusions.join(', ')}.
4. SHARP EDGES: Ensure the mask has crisp, sharp boundaries. NO BLUR, NO GRADIENTS, NO GRAYSCALE.
5. ACCURACY: Carefully follow the architectural lines of the house.
6. OUTPUT: Return only a flat, 2D black and white silhouette mask image.`,
            },
          ],
        },
      }),
      90_000,
      'auto-mask',
    );

    let maskBase64 = '';
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        maskBase64 = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!maskBase64) {
      return res.status(500).json({ error: 'No mask was generated by the AI model.' });
    }

    res.json({ maskBase64 });
  } catch (err: any) {
    console.error('[auto-mask] error:', err?.message);
    res.status(500).json({ error: err?.message || 'Auto-mask generation failed.' });
  }
}
